### ISSUE TITLE
个人博客头像显示问题

### ISSUE THREAD

**Issue by Aning3020** [Aning3020/Aning3020.github.io#1]
### 非技术人员，真心向各位高深人士请教。 共有两处，第一处是主页的头像。路径在siderbar/index/defaut.html都有涉及，我现在使用的是本地相对路径：/image/avatar.png。问题结果呈现如图：
上图是在本地预览／
<img width="294" alt="default" src="https://user-images.githubusercontent.com/20737239/30311903-f4fa9706-97c9-11e7-872a-a68b48fd190f.png">
下图是上传后预览：
<img width="283" alt="default" src="https://user-images.githubusercontent.com/20737239/30311918-067d0eb4-97ca-11e7-8fa9-eeed2f370558.png">
### 另一处是我的文章里，在post.html里有涉及此路径显示，我仍旧使用的本地路径。
上图是上线后／下图是本地预览：
<img width="301" alt="2" src="https://user-images.githubusercontent.com/20737239/30312321-84e6de46-97cb-11e7-8c2d-64d01f37368b.png">
<img width="280" alt="1" src="https://user-images.githubusercontent.com/20737239/30312317-8183fcde-97cb-11e7-88a6-0a43d622726c.png">
### 我自己也有把路经改成网络的路径：https://github.com/BleuHu/BleuHu.github.io/blob/master/image/avatar.png?raw=true
但是仍旧在本地能显示，同步上传后显示不了。

**Comment by BleuHu** [comment]
就是路径的事儿。
自己已经解决，自己查找图片路径的url之前有点问题，现在已经解决。右键图片直接有复制链接。就好啦。

**Comment by Aning3020** [comment]
**之前找图片路径url有问题，右键之后会出现复制链接，那个url就是最全最正确的路径**
_Happy ending._
