### ISSUE TITLE
如何将博客的Archives归档页变成那样？

### ISSUE THREAD

**Issue by Aning3020** [Aning3020/Aning3020.github.io#18]
## 我的背景

自己会一点 html 和 css ，但是不会 js 。我使用的 hexo 主题为：[Haojen/hexo-theme-Claudia: 📌 Concisely designed & easy to config, match device dark mode, 90+ Lighthouse scoring](https://github.com/Haojen/hexo-theme-Claudia)，自己改了一点css，去除了主页图片。

## 目标
我的目标为，将自己博客的归档页：[阿宁's blog](https://www.huyuning.com/archives/) 变成下面这样：
1. [Level Up](https://aiellochan.com/archives/)
2. [zblog](http://zhangshiying.in/archives/)
3. [archive | Hexo](https://lotabout.me/hexo-theme-noise/archives/)

这样的归档页面**只把文章标题按照年来归档，左侧是日期，右侧是对样的文章标题链接**

## 现状

当前我自己的博客归档页长这样：[阿宁's blog](https://www.huyuning.com/archives/) ，左侧部分调用了博客主页的 post-list 内容。这样的归档页和主页没啥两样，看着太重了。

## 中间自己的折腾出的一些观察
1. 了解到我需要修改的归档页由这页代码控制：[hexo-theme-Claudia/archive.pug](https://github.com/Haojen/hexo-theme-Claudia/blob/master/layout/archive.pug)
2. 这页代码由 pug 写的： [Template Inheritance – Pug](https://pugjs.org/language/inheritance.html#block-append-prepend)，[精通 Pug 樣版語言（一）語法基礎篇 | Blog - 白花殿](https://www.shirohana.me/blog/articles/2020-mastery-pug-template-engine)
3. 我的目标页归档代码可能长这样：[hexo-theme-noise/postarchive.pug at master · lotabout/hexo-theme-noise](https://github.com/lotabout/hexo-theme-noise/blob/master/layout/_partial/postarchive.pug)

**Comment by ZoomQuiet** [comment]
@Aning3020 找Hexo 的对应 theme 就好的哪

**Comment by Aning3020** [comment]
@ZoomQuiet 找到对应的theme啦，只是不想换成能变成目标样式的 theme ，这样会损失目前 theme 的其他功能。
我在自己折腾一下看看

**Comment by ZoomQuiet** [comment]
@Aning3020 囧...反过来想一下哈:

- 其它都是自己定制过的, 只有 归档不清楚
- 那么, 先用目标 theme 完成 归档的重构
- 其它的人工再定制一遍就好?

> @ZoomQuiet 找到对应的theme啦，只是不想换成能变成目标样式的 theme ，这样会损失目前 theme 的其他功能。 我在自己折腾一下看看

**Comment by Aning3020** [comment]
dama ,所以我为啥不直接在这个theme人工定制，这个只需要定制一个，换一个要定制好几个功能 = =

**Comment by Aning3020** [comment]
在竹子的帮助下改好啦，关闭 issue.

**Comment by ZoomQuiet** [comment]
> 在竹子的帮助下改好啦，关闭 issue.

@Aning3020 不是, 等等, Issue 的关闭并不是简单的一个结果哈,
而是值得具体分享:

+ 什么问题
+ 自己卡在哪儿
+ 在竹子的帮助是什么
+ 具体成果代码关键...
+ 自己思路被打开了什么
+ ...

没有总结就没有进步, 如何防止下次同类问题不被卡?
分享出来, 教会未来的自己
